spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/baedalmarket
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_size: 100
logging.level:
  org.hibernate.SQL: debug
